### ISSUE TITLE
kola: etcd1 tests fail

### ISSUE THREAD

**Issue by mischief** [coreos/mantle#100]
etcd1 tests fail because etcdctl now tries to reach a uri which 404s with etcd1. we either need to rewrite the tests to use e.g. curl for etcd1, or nuke the tests.

**Comment by philips** [comment]
I thought we decided to just stop testing etcd1.

**Comment by mischief** [comment]
@philips i am all for that, and will remove the tests if that is what is agreed upon.

**Comment by philips** [comment]
@pbx0 will write a test to cover this using the go libraries.

**Comment by pbx0** [comment]
https://github.com/coreos/mantle/pull/116 should fixes this

**Comment by mischief** [comment]
fixed via #116
