### ISSUE TITLE
Consider disabling Zincati/pinger in kola tests by default

### ISSUE THREAD

**Issue by bgilbert** [coreos/mantle#1017]
On Container Linux, update_engine doesn't check into CoreUpdate until 7 minutes after startup, so it's unlikely to do so during a kola run.  On FCOS, if Zincati or pinger want to check in much more quickly than that, we should disable them in kola tests to avoid spurious checkins.

cc @lucab @rfairley

**Comment by lucab** [comment]
fcos-pinger already supports that via a `reporting.enabled = true` snippet with high enough priority, see https://github.com/coreos/fedora-coreos-pinger#disabling-reporting.

Zincati does not yet support that, the relevant ticket to track is https://github.com/coreos/zincati/issues/62.
