### ISSUE TITLE
`plume release --distro fcos` failing with NoCredentialProviders

### ISSUE THREAD

**Issue by jlebon** [coreos/mantle#1023]
```
+ coreos-assembler shell plume release --distro fcos --version 30.20190712.dev.1 --channel testing-devel --bucket fcos-builds
2019-07-12T20:31:38Z plume: updating object ACLs: listing bucket: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

The way this works for the other AWS commands in the pipeline (which literally just use the `aws` CLI) is through the `AWS_CONFIG_FILE` env: https://github.com/coreos/fedora-coreos-pipeline/blob/2ec20a4f90550fd5942e41d7ff60f2581b301e40/manifests/pod.yaml#L20

Is this not something that plume understands?

**Comment by arithx** [comment]
It does understand that. Is it under the `default` profile in the config file?

**Comment by jlebon** [comment]
Yup, it's:

```
[default]
aws_access_key_id=xxx
aws_secret_access_key=xxx
```

**Comment by arithx** [comment]
https://github.com/coreos/fedora-coreos-pipeline/pull/98

I submitted a PR which directly specifies the `AWS_CONFIG_FILE` via the `--aws-credentials` parameter.

**Comment by arithx** [comment]
It looks like the issue stems from the `AWS_CONFIG_FILE` environment variable being considered a Shared Config key by the SDK. The code path that mantle traverses through the SDK results in us hitting the [`loadEnvConfig` function](https://github.com/coreos/mantle/blob/master/vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go#L161-L164) which checks the `AWS_SDK_LOAD_CONFIG` environment variable for a truthy value to determine if shared environment keys should be accepted.

As such this should be resolved by either specifying the credentials file directly (as done in coreos/fedora-coreos-pipeline#98) or by setting the `AWS_SDK_LOAD_CONFIG` environment varible to a truthy value.

Does that resolve your issue?

**Comment by jlebon** [comment]
We'll know in a bit; the build is still running and it's the last step in the pipeline.

**Comment by jlebon** [comment]
> or by setting the `AWS_SDK_LOAD_CONFIG` environment varible to a truthy value

This does work too BTW.

From https://docs.aws.amazon.com/sdk-for-go/api/aws/session/, it seems like this would also work:

```diff
diff --git a/platform/api/aws/api.go b/platform/api/aws/api.go
index f360397b..1a9e8869 100644
--- a/platform/api/aws/api.go
+++ b/platform/api/aws/api.go
@@ -79,6 +79,7 @@ func New(opts *Options) (*API, error) {
        }

        sess, err := session.NewSessionWithOptions(session.Options{
+               SharedConfigState: session.SharedConfigEnable,
                Profile: opts.Profile,
                Config:  awsCfg,
        })
```

Though I haven't tried it.
