### ISSUE TITLE
aws: Add retry detection to tag creation

### ISSUE THREAD

**Issue by arithx** [coreos/mantle#1030]
The current function for [tagging resources](https://github.com/coreos/mantle/blob/master/platform/api/aws/ec2.go#L229-L249) has no built in retries and returns a custom error which doesn't allow the caller to perform it. This can cause entire operations to fail due to eventual consistency issues.

Either a built-in set of retry characteristics should be constructed or we should return the direct error from the `a.ec2.CreateTags` call and allow the caller to perform these checks directly.

This was discovered by the FCOS release process failing when creating an AWS image via `ore aws upload` where after polling for the AMI to exist it attempted to tag it with a name and died to a `InvalidAMIID.NotFound` error.

**Comment by bgilbert** [comment]
It's interesting that we've never hit this before.
