### ISSUE TITLE
Make download-image work for FCOS

### ISSUE THREAD

**Issue by arithx** [coreos/mantle#1098]
# Feature Request #

## Desired Feature ##

With the removal of CL from the master branch the download-image code should be updated to be able to pull the latest FCOS images for different branches. The `cork download-image` command should also probably be moved to a different command (maybe `ore`? Every other piece of `cork` functionality should probably be dropped).

## Example Usage ##

`<cmd> download-image --stream testing`

**Comment by bgilbert** [comment]
Maybe it should be a subcommand of coreos-installer?

**Comment by bgilbert** [comment]
https://github.com/coreos/coreos-installer/pull/78

**Comment by cgwalters** [comment]
I think this is fixed now that mantle is merged into coreos-assembler, and coreos-assembler includes mantle by default.

**Comment by bgilbert** [comment]
cork was dropped from mantle `master` and the functionality is in `coreos-installer download` now.
