### ISSUE TITLE
Fix `ore aws copy-image` to copy snapshot permissions too

### ISSUE THREAD

**Issue by cgwalters** [coreos/mantle#1111]
Currently the OpenShift installer uses the underlying snapshot to make customer-private encrypted AMIs, so it needs to be public.  RHCOS doesn't use plume which makes snapshots public today.

Let's change `ore aws copy-image` to also propagate permissions for snapshots.

**Comment by miabbott** [comment]
A bit more context:

The RHCOS build pipeline switched from using a custom script for copying AMIs between regions to using `ore aws copy-image` invoked via `coreos-assembler aws-replicate`.  This change resulted in the the underlying snapshot that backs the AMIs in different regions to not have the `createVolumePermission` for all regions.

The follow-on effect is that the OCP installer is not able to successfully copy the snapshot in regions other than `us-east-1`.
