### ISSUE TITLE
Support arch exclusion for Kolet tests

### ISSUE THREAD

**Issue by Prashanth684** [coreos/mantle#1132]
I encountered one problematic case, where for s390x, the `TestNetworkScripts` test of rhcos was failing on s390x because some scripts were present in /etc/sysconfig/network-scripts. On further discussions with s390x folks, it looks like the scripts are needed by the udev machinery to bring up s390x network devices.

With  this being the case, I am looking to see if we can add support for arch exclusion for the tests which are run through kolet and wondering what is the best way to go about doing this.

We can have an arch exclusion list for each test and evaluate the list before starting to execute the tests. Any suggestions/thoughts?

**Comment by jlebon** [comment]
Fixed in https://github.com/coreos/mantle/pull/1131.

**Comment by Prashanth684** [comment]
@jlebon i opened this for making the native tests arch specific. today the overall test itself can be exclude per arch with #1131 but i want that control for individual kolet tests too . For example:

```
NativeFuncs: map[string]func() error{
			"PortSSH":        TestPortSsh,
			"DbusPerms":      TestDbusPerms,
			"NetworkScripts": TestNetworkScripts,
			"ServicesActive": TestServicesActiveCoreOS,
			"ReadOnly":       TestReadOnlyFs,
			"Useradd":        TestUseradd,
			"MachineID":      TestMachineID,
		},
```
I want  to be able to disable `TestNetworkScripts` for s390x alone.

**Comment by jlebon** [comment]
Ahh gotcha, thanks for clarifying. Re-opening!
