### ISSUE TITLE
kola/jenkins: authenticate with GS to allow fetching from private buckets

### ISSUE THREAD

**Issue by marineam** [coreos/mantle#135]
The `imageroot` parameter in kola and kola-gce jobs should work with private buckets like builds.release.core-os.net so they can be used to test releases.

**Comment by pbx0** [comment]
kola-qemu
- [ ] create private-key-based GCE service account and store in jenkins
- [ ] read acess on builds.release.core-os.net granted to this key
- [ ] `cork download-image` needs to flag to accept private-key-based GCE service accounts
- [ ] `cork download-image` is passed secret from jenkins secret variable thing

kola-gce
- [ ] `cork download-image` can use just magic metadata service auth, just add a flag
- [ ] read acess on builds.release.core-os.net granted to this key

**Comment by pbx0** [comment]
Confirmed to be fixed in https://github.com/coreos/mantle/pull/179.
