### ISSUE TITLE
kola: comprehensive flannel tests

### ISSUE THREAD

**Issue by mischief** [coreos/mantle#147]
we need to have tests for flannel. currently, we cannot test flannel on our qemu target because it has no internet connectivity and thus cannot pull the docker image.

however, we can write tests for gce and aws, and test flannel's gce and aws-vpc backends.

**Comment by euank** [comment]
We have tests for flannel now https://github.com/coreos/mantle/tree/master/kola/tests/flannel.

They're not super comprehensive, but if we have specific things we need coverage on we should split out more issues.
