### ISSUE TITLE
kola: test kubernetes using CoreOS docs

### ISSUE THREAD

**Issue by pbx0** [coreos/mantle#214]
Currently, a kubernetes multi-node smoke test exists that uses a fairly direct translation of some upstream community docs. This test should have its cloud-configs replaced to use our own docs which include TLS and using the built-in CoreOS kubelet service file. This is important to test our built in kubelet binary (soon to be an aci).

**Comment by mischief** [comment]
fixed by #241 ?

**Comment by pbx0** [comment]
Indeed!
