### ISSUE TITLE
QEMU cluster does not stop ntp.Server

### ISSUE THREAD

**Issue by mischief** [coreos/mantle#216]
network/ntp.Server is brought up during qemu tests, but is never stopped.

/cc @marineam

**Comment by marineam** [comment]
It is stoppable, just need to call Close which is provided via an embedded interface: https://golang.org/pkg/net/#PacketConn

So just the qemu cluster needs fixing

**Comment by marineam** [comment]
Kinda disappointing that that godoc doesn't explicitly list things available via embedding, otherwise this would make it obvious: https://godoc.org/github.com/coreos/mantle/network/ntp#Server

Oh well. It's as if Go doesn't like subclassing or something :-P
