### ISSUE TITLE
kola: emit test results in a format jenkins can parse

### ISSUE THREAD

**Issue by mischief** [coreos/mantle#308]
using JUnit with https://github.com/jstemmer/go-junit-report seems like a good choice, since jenkins supports JUnit.

**Comment by marineam** [comment]
To be a bit more generic there is TAP:

http://testanything.org/
https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin
https://github.com/mndrix/tap.go

**Comment by mischief** [comment]
fixed by #310
