### ISSUE TITLE
Split --gce-project

### ISSUE THREAD

**Issue by pbx0** [coreos/mantle#427]
The flag `--gce-project` is used as both the gce-image-project and the gce-project. So if you want to use an image from a different project then the project on which machine's are spawned it can't be done. Gcloud differentiates these projects and we should too.

**Comment by bgilbert** [comment]
You can use e.g.

```
--gce-image projects/coreos-cloud/global/images/coreos-stable-1353-7-0-v20170427
```
or
```
--gce-image projects/coreos-cloud/global/images/family/coreos-alpha
```

**Comment by pbx0** [comment]
Ah, this issue was fixed awhile back by supporting those links.
