### ISSUE TITLE
evaluate Terraform for cloud provider integration into Kola

### ISSUE THREAD

**Issue by philips** [coreos/mantle#486]
Terraform has been working nicely for bootkube testing and elsewhere. Further, a bunch of users have been starting to integrate Terraform into their deployments.

It would be really useful to research if we could replace the code that spins-up/down and ssh's into servers with Terraform.

This would also help with enabling Azure and OpenStack testing for Ignition and Container Linux testing.

If you need any expertise in Terraform you can ping @s-urbaniak or @alexsomesan

cc @marineam @ethernetdan @pbx0

**Comment by philips** [comment]
@marineam could you take a look and evaluate the feasibility of this?

**Comment by bgilbert** [comment]
There's an initial implementation in #532, but we've opted not to pursue it further.  The reasons are, roughly:

- We need fine-grained control over how we interact with cloud providers, e.g. fetching instance console logs.
- kola works at a different level of abstraction than other Terraform-based test environments, so it'd be difficult to share a lot of code with them.
