### ISSUE TITLE
pluton: disable selinux automatically

### ISSUE THREAD

**Issue by pbx0** [coreos/mantle#516]
Kola tests have selinux enabled on all machines. This tends to break a few things in k8s land. While ultimately it'd be great to always enable, it causes pluton users with breakages that wouldn't occur on a stock Container Linux machine not setup via pluton. Creating and adding nodes to a bootkube cluster already hides this detail currently, however, if a user calls Reboot on a machine they have to manually re-disable selinux.

@yifan-gu Ran into this problem because the checkpointer pod in his test couldn't write out its lock file despite having correct permissions.

This could be tackled in a variety of ways. Mocking out the Machine interface used in pluton.Cluster is one.

**Comment by ajeddeloh** [comment]
Closing this since pluton has been dropped (https://github.com/coreos/mantle/pull/683).
