### ISSUE TITLE
pluton: collecting various test flakes

### ISSUE THREAD

**Issue by pbx0** [coreos/mantle#565]
[--- FAIL: bootkube.selfetcd.destruct.reboot (1700.77s)
        destructiontests.go:35: Unable to enable SELinux: ssh: unexpected packet in response to channel open: <nil>](https://jenkins-tectonic.prod.coreos.systems/job/bootkube-dev/651/console)
Seen 1 time

[ --- FAIL: bootkube.selfetcd.smoke (179.01s)
        run.go:148: creating cluster: failed to request new GCE instance: googleapi: Error 503: Code: '3530860079175192029', backendError](https://jenkins-tectonic.prod.coreos.systems/job/bootkube-dev/634/consoleFull)
Seen 1 time

**Comment by pbx0** [comment]
```
--- FAIL: bootkube.destruct.delete (1502.26s)
        run.go:147: creating cluster: populating cache: [scp'ing container : Process exited with status 1 -- ]
```
Seen 1 time

**Comment by ajeddeloh** [comment]
Closing this since pluton has been dropped (https://github.com/coreos/mantle/pull/683).
