### ISSUE TITLE
kola: Mechanism for flagging tests that need Internet access

### ISSUE THREAD

**Issue by bgilbert** [coreos/mantle#572]
Right now we're tagging these with `ExcludePlatform: []string{"qemu"}`, which is not ideal.

**Comment by euank** [comment]
Ideally, tests wouldn't need internet access either.

A lot of the tests needing internet access really need access to a docker registry, which the test framework should spin up (just as it does for an etcd cluster).

The registry could be populated from known images stored as artifacts in GCS
