### ISSUE TITLE
cork enter --experimental doesn't properly expose gpg agent socket

### ISSUE THREAD

**Issue by bgilbert** [coreos/mantle#622]
It tries to bind the socket into `/run/user/UID/agent-NNNNNN/` and point `GPG_AGENT_INFO` at it.  `GPG_AGENT_INFO` is ignored by gpg &ge; 2.1, and gpg &ge; 2.1.13 expects to find the agent socket in `/run/user/UID/gnupg`.

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/mantle/pull/812
