### ISSUE TITLE
Where to put cloud provider credentials is not documented

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/mantle#731]
## Expected behavior:
The documentation states where to put credentials for each cloud provider (e.g. `~/.aws/credentials`)

## Actual behavior:
The documentation does not state where to put credentials.

**Comment by euank** [comment]
It should also give recommendations around placing it, e.g. for aws specifically you can do `emerge awscli; aws configure` in the sdk rather than constructing it by hand.

**Comment by ajeddeloh** [comment]
Oh neat, didn't know that.

**Comment by ajeddeloh** [comment]
Closed via https://github.com/coreos/mantle/pull/736
