### ISSUE TITLE
Automatically retry when DigitalOcean droplet creation fails

### ISSUE THREAD

**Issue by bgilbert** [coreos/mantle#760]
The DO API tells us when this occurs. Other clouds may do the same.

**Comment by arithx** [comment]
Was this completed in https://github.com/coreos/mantle/commit/8764da1602623e6fb13c8a782fd74bbe72d5457a or did you have a more intelligent retry system in mind?

**Comment by bgilbert** [comment]
I think 8764da1 should be sufficient for now.
