### ISSUE TITLE
GitHub bug wrangler

### ISSUE THREAD

**Issue by marineam** [coreos/mantle#8]
We need a new tool to help manage GitHub bugs, possible features include:

- View/sort bugs across repos
- View related bugs across repos (bug report and PR are often in different places)
- Update bugs as a fix rolls through the release process so people can track when it hits alpha, beta, stable.
- Help establish a pattern we can use to organize and prioritize bugs.

In short, we are terrible at tracking bugs right now. We need to fix that.

**Comment by demonbane** [comment]
Just gonna leave this here: https://waffle.io/ :+1:

**Comment by crawford** [comment]
CrawfordAPI v0.1
