### ISSUE TITLE
Platform aws only logs the console until the first reboot

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/mantle#800]
The `console.txt` logs in _kola_temp stop after the first reboot on aws. The logs should span reboots.

**Comment by bgilbert** [comment]
Right now we loop fetching logs until they are not empty, which could fail to pick up logs from the last boot if those show up a little later.

**Comment by ajeddeloh** [comment]
It looks like we only call that in machine.Destroy() for aws. Is your concern that there is latency on the aws side?

**Comment by bgilbert** [comment]
There is known to be latency on the AWS side; that's why we loop on AWS' `GetConsoleOutput`.  If the latency is per-boot, that would explain the problem we're seeing.

**Comment by ajeddeloh** [comment]
From [the aws docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html)
> Only the most recent 64 KB of posted output is stored, which is available for at least 1 hour after the last posting. 

running `stat consol.txt`:

```
  File: 'console.txt'
  Size: 65525           Blocks: 128        IO Block: 4096   regular file
...
```
Looks like we're (nearly?) hitting the 64k limit.

**Comment by bgilbert** [comment]
We should still be getting the last boot, not the first one.

**Comment by ajeddeloh** [comment]
yeah, It might make sense to grab it every boot, reboot, and termination. They might have overlap, so I think it makes sense to save them as seperate files instead of trying to de-dup. The console checks would have to be run on all of them.
