### ISSUE TITLE
kola: Capture complete console logs on AWS

### ISSUE THREAD

**Issue by arithx** [coreos/mantle#859]
Some `kola` runs on AWS do not capture the complete console logs.

`docker.torcx-manifest-pkgs` is usually a good test subject.

**Comment by bgilbert** [comment]
Is this different than #800/#802?  AWS snapshots the logs at specific times and only gives us 64 KB per snapshot.

**Comment by bgilbert** [comment]
They only snapshot 5 minutes after boot, 5 minutes after reboot, and at shutdown.
