### ISSUE TITLE
Kola fails on AWS if the kola security group doesn't have a VPC attached

### ISSUE THREAD

**Issue by yuqi-zhang** [coreos/mantle#914]
Minor bug: If the VPC gets pruned, but the security group is not deleted, it will cause a failure like:

`error resolving subnet: no subnets found for vpc vpc-xxxxxx`

Can be worked around by deleting security group and have Kola re-create everything.

**Comment by bgilbert** [comment]
I talked with @yuqi-zhang OOB and he doesn't think this is likely to be a recurring issue in our environment.

**Comment by arithx** [comment]
Closing WONTFIX. We're planning on adding `ore` commands to create & delete networking resources https://github.com/coreos/mantle/issues/992 rather than creating them if they're not found during a `kola` run. With that change the answer will be to just delete & recreate the networking resources.
