### ISSUE TITLE
OS ID detection improvements

### ISSUE THREAD

**Issue by cgwalters** [coreos/mantle#918]
The `cmd/kola/options.go:    kolaDistros        = []string{"cl", "rhcos"}` approach is now a problem - I'm trying to push forward with making FCOS and many tests will work on it as well.

Maybe a simple thing to do would be to have an `FEDORA_COREOS_ALIKE=yes` variable in the `os-release` file - that could mean "has Ignition and OSTree" at least.  (Gets interesting when we start to talk about e.g. `docker`).

**Comment by cgwalters** [comment]
This blocks https://github.com/coreos/coreos-assembler/pull/85

**Comment by arithx** [comment]
I'm planning on doing a similar thing for FCOS I did for RHCOS once I get the OpenStack platform pushed up. In the interim nothing (short of some tests just not working against FCOS) should be blocking you from using the `rhcos` distribution option (as it doesn't have any built-in checks like CL does for `Version`).

**Comment by cgwalters** [comment]
https://github.com/coreos/mantle/pull/920 is a first step.

**Comment by bgilbert** [comment]
We opted to explicitly list the OSes that a test should apply to.  Closing.
