### ISSUE TITLE
a couple licensing questions

### ISSUE THREAD

**Issue by dustymabe** [coreos/mantle#966]
- What is the point of https://github.com/coreos/mantle/blob/master/update/metadata/LICENSE ? 
- This [file](https://github.com/coreos/mantle/blob/master/platform/api/azure/storage_mit.go) is MIT licensed because it was *"derived from https://github.com/Microsoft/azure-vhd-utils/blob/8fcb4e03cb4c0f928aa835c21708182dbb23fc83/vhdUploadCmdHandler.go"* ?

**Comment by bgilbert** [comment]
- That LICENSE file was imported in 592e01f8c4a5e1efaff13a1f341093ba6d034b37 and covers https://github.com/coreos/mantle/blob/master/update/metadata/update_metadata.proto, as mentioned in the latter's header.
- Correct.

**Comment by dustymabe** [comment]
👍
