### ISSUE TITLE
ppc64le: Test fail on said architecture

### ISSUE THREAD

**Issue by r4f4** [coreos/mantle#971]
Building `mantle` on ppc64le seems to have been successful. However I get an error when running the tests:
```
# make test
Checking gofmt...
Checking govet...
Running commands...
 Running cork...
 Running gangue...
 Running kola...
panic: No portage arch defined for ppc64le

goroutine 1 [running]:
github.com/coreos/mantle/system.PortageArch(...)
	/root/coreos-assembler/mantle/gopath/src/github.com/coreos/mantle/system/arch.go:37
github.com/coreos/mantle/sdk.DefaultBoard(0x118bda46, 0x18)
	/root/coreos-assembler/mantle/gopath/src/github.com/coreos/mantle/sdk/repo.go:87 +0xb8
make: *** [Makefile:6: test] Error 2
```

**Comment by r4f4** [comment]
Commenting the fall-through for `ppc64le` in `system/arch.go:37` the tests seem to succeed. Anything I'm overlooking here?

Changes:
```
diff --git a/build b/build
index 44914a4a..6faf1ac2 100755
--- a/build
+++ b/build
@@ -22,7 +22,7 @@ host_build() {
 
 cross_build() {
        local a
-       for a in amd64 arm64; do
+       for a in amd64 arm64 ppc64le; do
                echo "Building $a/$1"
                mkdir -p "bin/$a"
                CGO_ENABLED=0 GOARCH=$a \
diff --git a/system/arch.go b/system/arch.go
index 06f0b00b..a5f6b4cc 100644
--- a/system/arch.go
+++ b/system/arch.go
@@ -32,7 +32,7 @@ func PortageArch() string {
 
        // Gentoo doesn't have a little-endian PPC port.
        case "ppc64le":
-               fallthrough
+               //fallthrough
        default:
                panic("No portage arch defined for " + arch)
        }
```

```
 # make test
./test
Building tests...
Running tests...
[...]
Checking gofmt...
Checking govet...
Running commands...
 Running cork...
 Running gangue...
 Running kola...
 Running kolet...
 Running ore...
 Running plume...
Success
```

**Comment by arithx** [comment]
The [`DefaultBoard` function in `sdk/repo.go`](https://github.com/coreos/mantle/blob/master/sdk/repo.go#L87) calls `PortageArch` and is used in two places that are *COS facing [`cmd/kola/options`](https://github.com/coreos/mantle/blob/master/cmd/kola/options.go#L31) & [`cmd/plume/specs`](https://github.com/coreos/mantle/blob/master/cmd/plume/specs.go#L402), in both cases building a list of the supported boards.

`PortageArch` isn't relevant to *COS and as such these declarations should be changed. This will likely fall under the [multi-arch refactor](https://github.com/coreos/mantle/issues/943).

**Comment by dustymabe** [comment]
How hard would the multi-arch refactor be to pull off? Is this something a new contributor could do (i.e. @r4f4 ?)

**Comment by arithx** [comment]
@dustymabe the multi-arch refactor shouldn't be exceptionally difficult code-wise, provided an understanding of the current code & what CL defines as a `board`.

Off the top of my head, it would entail multiple platform tweaks, adding a new set of functionality into the `Flight`, and some harness/runner modifications on the `kola` & `ore` side. There would also probably be some minor changes in `plume` & `cork` to support using whatever new architecture fetching functions exist.

One of the main time consuming things I see with the re-work is going to be the testing requirement before such a change lands but that's something that could be eaten at review time.

As well, the current proposal for cleaning up multi-arch support isn't the most well defined issue. I'll try to grab some time to think through what I'd like to see in a multi-arch refactor and potentially grab some of @bgilbert's time as well.

**Comment by arithx** [comment]
I've posted an update in #943 about goals for a multi-arch refactor

**Comment by dustymabe** [comment]
@r4f4 - any chance you'd like to take a stab at #943 considering [the direction given by @arithx](https://github.com/coreos/mantle/issues/943#issuecomment-462929644)

**Comment by r4f4** [comment]
@dustymabe sure. It'll be a slow process since I don't know Go but I'll try.

**Comment by jcajka** [comment]
I have opened https://github.com/coreos/mantle/pull/1067 that allows the mantle/kola to be built. Test still fail. It seems that it might be a randomness issues in the VM as ```A start job is running for…er Key Generation``` do not finishes and the VM is refusing the ssh connection. I'm continuing investigating it.

**Comment by jcajka** [comment]
For the record https://github.com/coreos/mantle/pull/1067 got merged, with fix for the randomness. I believe this can be closed as both ```make test``` and ```cosa kola run``` should be passing on the ppc64le at the moment.
