### ISSUE TITLE
Ignition 3.0.0 Support

### ISSUE THREAD

**Issue by arithx** [coreos/mantle#974]
Ignition 3.0.0 is being actively worked on and is something that we should be running through additional testing via `kola`.

As the 3.0.0 spec will not be backwards compatible we will need to have a mechanism for declaring what Ignition version the distribution under test is running that can change out both the underlying config generation as well as some test level user-data to supported configuration versions.

Initially it might make sense to at least get a branch setup that drops Ignition 1.x & 2.x support and updates existing test configurations to 3.0.0 specs. Although that will create a large maintenance burden.

**Comment by ajeddeloh** [comment]
One option is to ~~boil the ocean~~ switch to go modules in both Ignition and mantle and cut a 2.0.0-development release of Ignition (Ignition, not the spec). This would allow both versions to be vendored at the same time.

This is also somewhat moot until we get Ignition 3.0.0 in FCOS, which is largely dependent on landing the FS rework and the corresponding change to `ignition-dracut`.
