### ISSUE TITLE
`kola spawn` doesn't work with FCOS

### ISSUE THREAD

**Issue by miabbott** [coreos/mantle#981]
I know that FCOS isn't even ready, but putting this out there...

I built an FCOS image locally via `coreos-assembler` and tried to boot it with `kola spawn`

```
$  sudo ./bin/kola spawn -b fcos --qemu-image /var/srv/fedora-coreos/builds/latest/fedora-coreos-29-qemu.qcow2                                  
Spawning instance failed: machine "24d5b086-5fb3-45f1-af7a-8f1c169c1a04" failed to enable selinux: Unable to enable SELinux: Process exited with status 1: We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
```

This also affects the ability to `kola run` any tests against FCOS, obviously.

Might be a configuration issue on FCOS that we can fix in `fedora-coreos-config`, but I haven't dug in.

**Comment by bgilbert** [comment]
Thanks for reporting.  From the symptoms, this is probably https://github.com/coreos/fedora-coreos-config/issues/41.  I'll close as duplicate.

**Comment by ashcrow** [comment]
FWIW: We now see the same issue in RHCOS on qemu.
