### ISSUE TITLE
enable `kola` to test oscontainers

### ISSUE THREAD

**Issue by miabbott** [coreos/mantle#987]
In the near future, the build pipeline for RHCOS will not be producing AMIs at the same cadence as `oscontainers`.  This presents a problem for using `kola` to test new RHCOS content, as we expect to have an AMI to test against.

I think we'd like to be able to provide something like a `registry/container@sha256sum` value via a flag to `kola run`, which would instruct the hosts to upgrade to that `oscontainer` before running any test.  @cgwalters suggested we use Ignition to pivot the host under test to the desired `oscontainer`

**Comment by cgwalters** [comment]
We probably want to bifurcate this and support a "plain" ostree repo + target commit as well.

This could be something like `kola --oscontainer=registry/container@sha256` which would be implemented by writing out Ignition to do the same thing the MCD does, which is here:

https://github.com/openshift/pivot/#example-usage

The FCOS case would be something like `kola --ostree-repo=example.com/somerepo --rpmostree-rebase=fedora/29/x86_64/testing/coreos`

**Comment by arithx** [comment]
I think this would likely require some runner / harness level hooks to implement properly. Even if we automatically inject a systemd unit that pivots & reboots in the Ignition config I'm not sure that would play nicely with all of the individual tests.

For one, I'm not sure if the runner would intelligently wait until after the reboot has happened to hand over the test machine. I'd guess that there'd be flakiness in that the test runner might see the machine as booted, do the sanity checks that the machine has booted properly, hand it off to the test runner, and then the pivot reboot triggers and the test itself has an unexpected offline machine causing the test to fail when it attempts to do SSH operations.

**Comment by cgwalters** [comment]
> Even if we automatically inject a systemd unit that pivots & reboots in the Ignition config I'm not sure that would play nicely with all of the individual tests.

Doesn't kola mostly run tests via ssh?  We'd pivot before ssh comes up, same as how RHCOS `pivot.service` has `Before=kubelet.service`.

**Comment by arithx** [comment]
If it's properly gated before SSH then I believe it _should_ play nicely with everything; The `NewMachine` call on clusters call `StartMachine` which performs the [`CheckMachine` function](https://github.com/coreos/mantle/blob/master/platform/platform.go#L310) as part of it (which SSH's onto the machine to ensure that no systemd units failed).
